### ISSUE TITLE
Failure compiling maxsimplex on OS X

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#125]
The following happens on Mac OS X 10.11.6, when trying to compile Normaliz 3.1.2 with `Apple LLVM version 8.0.0 (clang-800.0.42.1)`:
```
$ make
[ 63%] Built target normaliz-shared
[ 81%] Built target normaliz
[ 90%] Linking CXX executable maxsimplex
Undefined symbols for architecture x86_64:
  "long long libnormaliz::v_scalar_product<long long>(std::__1::vector<long long, std::__1::allocator<long long> > const&, std::__1::vector<long long, std::__1::allocator<long long> > const&)", referenced from:
      lattice_widths(libnormaliz::Cone<long long>&) in maxsimplex.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [maxsimplex/CMakeFiles/maxsimplex.dir/build.make:98: maxsimplex/maxsimplex] Error 1
make[1]: *** [CMakeFiles/Makefile2:274: maxsimplex/CMakeFiles/maxsimplex.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```
So this looks like a templateing problem -- `v_scalar_product` was not instantiated for `long long`.

I also tried with GCC 5.4 and 6.3, but both also produce an error (albeit a different one):
```
[ 63%] Linking CXX shared library libnormaliz.dylib
Undefined symbols for architecture x86_64:
  "operator<<(std::basic_ostream<char, std::char_traits<char> >&, __mpq_struct const*)", referenced from:
      libnormaliz::Full_Cone<long>::print() const in libnormaliz-templated.cpp.o
      libnormaliz::Full_Cone<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> >::print() const in libnormaliz-templated.cpp.o
      libnormaliz::Full_Cone<long long>::print() const in libnormaliz-templated.cpp.o
  "operator<<(std::basic_ostream<char, std::char_traits<char> >&, __mpz_struct const*)", referenced from:
      libnormaliz::operator<<(std::basic_ostream<char, std::char_traits<char> >&, libnormaliz::HilbertSeries const&) in HilbertSeries.cpp.o
      libnormaliz::HilbertSeries::to_string_rep[abi:cxx11]() const in HilbertSeries.cpp.o
      libnormaliz::Matrix<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> >::print(std::basic_ostream<char, std::char_traits<char> >&) const in libnormaliz-templated.cpp.o
      std::basic_ostream<char, std::char_traits<char> >& libnormaliz::operator<< <__gmp_expr<__mpz_struct [1], __mpz_struct [1]> >(std::basic_ostream<char, std::char_traits<char> >&, std::vector<__gmp_expr<__mpz_struct [1], __mpz_struct [1]>, std::allocator<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> > > const&) in libnormaliz-templated.cpp.o
      unsigned long libnormaliz::decimal_length<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> >(__gmp_expr<__mpz_struct [1], __mpz_struct [1]>) in libnormaliz-templated.cpp.o
      libnormaliz::Matrix<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> >::maximal_decimal_length_columnwise() const in libnormaliz-templated.cpp.o
      libnormaliz::Matrix<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> >::pretty_print(std::basic_ostream<char, std::char_traits<char> >&, bool) const in libnormaliz-templated.cpp.o
      ...
  "operator>>(std::basic_istream<char, std::char_traits<char> >&, __mpz_struct*)", referenced from:
      libnormaliz::HilbertSeries::from_string_rep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in HilbertSeries.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [libnormaliz/CMakeFiles/normaliz-shared.dir/build.make:227: libnormaliz/libnormaliz.3.1.2.dylib] Error 1
make[1]: *** [CMakeFiles/Makefile2:219: libnormaliz/CMakeFiles/normaliz-shared.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

Any ideas as to what goes wrong and how to overcome this?

**Comment by w-bruns** [comment]
The first problem occurring for CLANG is most likely caused by the fact that the compiler makes the templated v_scalar_product an inlined function. In version 3.2.0 it will be forced to be compiled independently. Such surprises cannot be foreseen.

The second problem seem s to be caused by the GMP C++ wrapper, as far as I can see.

Please don't use 3.1.2. It contains a bug. (If it occurs it is shown by a failed assert.) It is better to switch to 3.1.4.

**Comment by w-bruns** [comment]
PS. For the time being, have a look at the end vector_operations.cpp and add instantiations of v_scalar_product.

**Comment by fingolfin** [comment]
I've used 3.1.2 because that is the östest version advertised on the Normaliz homepage... though in some places, 3.1.1 is listed as latest... so, is the homepage outdated?

**Comment by fingolfin** [comment]
I am also surprised by the statement "Such surprises cannot be foreseen." -- I thought you are using Travis to catch such issues? Or perhaps everything is working ther?

**Comment by w-bruns** [comment]
The homepage indeed needs to be updated. But since you got 3.1.2 from GitHub, you should have seen that there are newer releases.

Our Travis builds are all o.k., with GCC and CLang.

**Comment by fingolfin** [comment]
No, I couldn't see it, because all I did was to update the version from 3.1.1 to 3.1.2 in a script which downloads normaliz from github (a script that is bundled with `NormalizInterface`). I never visited the github repository myself, before submitting this issue :-).

Anyway, I now switched to the master branch, and this issue is gone. Thanks!
