### ISSUE TITLE
Building static library with e-antic fails

### ISSUE THREAD

**Issue by mahrud** [Normaliz/Normaliz#426]
I think `-lflint -lgmp` are missing in this line:
https://github.com/Normaliz/Normaliz/blob/6ea5ca5a5dd14478c96e354053528125225e3e95/configure.ac#L437

Without them, if I build the `conftest.cpp` file I get a gigantic linking error starting with:
```
$ g++-14 conftest.cpp -leanticxx -leantic 
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libeanticxx.a(renf_elem_class.o): in function `eantic::renf_elem_class::renf_elem_class(eantic::renf_class const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
renf_elem_class.cpp:(.text+0xff0): undefined reference to `flint_malloc'
/home/linuxbrew/.linuxbrew/bin/ld: renf_elem_class.cpp:(.text+0x100e): undefined reference to `fmpq_poly_init'
...
collect2: error: ld returned 1 exit status
```
or if I add only `-lflint`:
```
$ g++-14 -o conftest -g -O2 conftest.cpp  -leanticxx -leantic -lflint
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libeanticxx.a(renf_elem_class.o): undefined reference to symbol '__gmpz_init'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libgmp.so.10: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
As far as I can tell the only way around it is setting `LDFLAGS="-lflint -lgmp"`, but why not just include this in there?

**Comment by mahrud** [comment]
Actually, even setting LDFLAGS doesn't work:
```
$ g++ -std=gnu++14 -o conftest -g -O2 -lflint -lgmp     conftest.cpp  -leanticxx -leantic
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libeanticxx.a(renf_elem_class.o): in function `eantic::renf_elem_class::renf_elem_class(eantic::renf_class const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
renf_elem_class.cpp:(.text+0x1386): undefined reference to `flint_malloc'
/usr/bin/ld: renf_elem_class.cpp:(.text+0x13a7): undefined reference to `fmpq_poly_init'
/usr/bin/ld: renf_elem_class.cpp:(.text+0x1403): undefined reference to `fmpq_poly_clear'
/usr/bin/ld: renf_elem_class.cpp:(.text+0x140b): undefined reference to `flint_free'
...
```
Because the _order_ is important too! This works:
```
$ g++ -std=gnu++14 -o conftest -g -O2 conftest.cpp  -leanticxx -leantic -lflint -lgmp     
```
I'm really curious why this is only problematic on some systems.

**Comment by w-bruns** [comment]
I am confused. Which systems are problematic and which are not?

**Comment by mahrud** [comment]
Yes, I agree, but using `LDFLAGS="-lflint -lgmp" ./configure ... --with-e-antics` this line is used:
```
$ g++ -std=gnu++14 -o conftest -g -O2 -lflint -lgmp     conftest.cpp  -leanticxx -leantic
```

**Comment by mahrud** [comment]
The configure step is failing on ubuntu 24.04 for me, but works fine on macs and fedora.

**Comment by w-bruns** [comment]
The machines that I can use have Ubuntu 2.04. But one can ask for ubuntu-24.04 on GitHub. I will try it.

**Comment by w-bruns** [comment]
The build with "extended" in its name, the most extensive Linux test, worked well with 24.04. It uses the Normaliz install script for e-antic.

**Comment by mahrud** [comment]
What does that have to do with this issue? I don't want to build every dependency from source to get Normaliz working. If that's not a concern, feel free to close this issue as not planned.

**Comment by mahrud** [comment]
Maybe I should emphasize that I'm trying to build a _static_ library, using a static libeantic. I just tried using your extended test, with the following addition:
```
root@6cad677f1a89:~# rm local/lib/libeantic*so*
root@6cad677f1a89:~# CPPFLAGS=-I/home/norm/local/include LDFLAGS="-L/home/norm/local/lib -Wl,--enable-new-dtags -Wl,-rpath=/home/norm/local/lib" ./configure --with-e-antic
...
checking whether e-antic headers and library are available... configure: error: e-antic is not available in a supported version but was requested
```
Looking at `config.log`:
```
configure:20036: g++ -o conftest -g -O2 -I/home/norm/local/include      -L/home/norm/local/lib -Wl,--enable-new-dtags -Wl,-rpath=/home/norm/local/lib      conftest.cpp  -leanticxx -leantic >&5
/usr/bin/ld: /home/norm/local/lib/libeanticxx.a(renf_elem_class.o): in function `eantic::renf_elem_class::renf_elem_class(eantic::renf_class const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/norm/nmz_opt_lib/E-ANTIC_source/e-antic-2.0.2/libeantic/srcxx/renf_elem_class.cpp:408:(.text+0x1374): undefined reference to `flint_malloc'
...
```
I can provide the whole log file if you'd like.

**Comment by w-bruns** [comment]
All I can say is that the standard method for building Noramliz builds libnormaliz.a and libnormaliz.so (or libnoemaliz.dylib), unless you suppress one of them. For both builds the static and shared versions of the auxiliary packages are used, ,resp., provided both exist: so far, nauty and CoCoALib only exist statically. 

You can see in the CI on GitHub that it is possible to link only a subset of the full set of auxiliary packages. Note that the compilation and linking is always by libtool. I think configure.ac is made for libtool. 

For development I use Makefile.classic in source in connection with Makefile.configuration. It produces a plain g++ command to compile a static normaliz.

The extended tests run by the build with "extended" in its name force Normaliz into variants made for large computations that  can't be realized in the standard test suite because they would take too long.

**Comment by w-bruns** [comment]
Can we close this issue?

**Comment by mahrud** [comment]
I don't think it would be too complicated to fix this issue, but sure, I will close it.
